services:
  app:
    build:
      context: .
    command: npm run start
    environment:
      NODE_ENV: production
      PORT: "3000"
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data:ro
      - ./reports:/app/reports
