from __future__ import annotations

from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path
from pathlib import PurePosixPath
import hashlib
import json
import subprocess
from typing import Any, Mapping


CLAIM_LABELS = {"demo", "proxy", "calibrated", "real-data", "procurement-ready"}


@dataclass(slots=True)
class DataSource:
    id: str
    label: str
    path: str
    claim_label: str
    source_type: str
    available: bool
    sha256: str | None = None
    bytes: int | None = None
    freshness: str = "local workspace snapshot"
    notes: str = ""


def build_run_passport(
    *,
    run_id: str,
    scenario_params: dict[str, Any],
    seed: int | None,
    claim_labels: dict[str, str] | None = None,
    data_sources: list[dict[str, Any]] | None = None,
    limitations: list[str] | None = None,
    calibration_path: str | Path = "data/calibration/almaty_calibration_layer.json",
    root: str | Path = ".",
    source_paths: Mapping[str, str | Path] | None = None,
    source_refs: Mapping[str, str] | None = None,
    project_context: Mapping[str, Any] | None = None,
    calibration_context: Mapping[str, Any] | None = None,
) -> dict[str, Any]:
    """Build a serializable run passport for audit and dossier outputs.

    Legacy callers may rely on ``root`` and ``calibration_path``. A staging
    caller passes the three explicit contexts instead; that mode is closed and
    never fills a missing source or project field from the repository root.
    """

    root_path = Path(root)
    labels = _normalize_claim_labels(
        claim_labels
        or {
            "roads": "real-data",
            "traffic": "demo",
            "analytics": "proxy",
            "calibration": "proxy",
            "dossier": "proxy",
        }
    )
    sources = default_data_sources() if data_sources is None else data_sources
    resolved_sources = _resolve_source_context(
        sources,
        root=root_path,
        source_paths=source_paths,
        source_refs=source_refs,
    )
    source_payload = [
        asdict(
            _source_from_config(
                source,
                root_path,
                physical_path=resolved_sources[str(source.get("id"))][0],
                source_ref=resolved_sources[str(source.get("id"))][1],
            )
        )
        for source in sources
    ]
    model = _project_context(root_path, project_context, explicit_sources=source_paths is not None)
    calibration = _resolved_calibration_context(
        calibration_path=calibration_path,
        calibration_context=calibration_context,
        resolved_sources=resolved_sources,
        explicit_sources=source_paths is not None,
    )
    return {
        "runId": run_id,
        "createdAt": datetime.now(timezone.utc).replace(microsecond=0).isoformat(),
        "model": model,
        "seed": seed,
        "scenarioParams": scenario_params,
        "dataSources": source_payload,
        "calibrationValidation": calibration,
        "limitations": limitations or default_limitations(),
        "claimLabels": labels,
        "audit": {
            "claimRule": "Use demo/proxy/calibrated/real-data/procurement-ready exactly; do not upgrade without evidence.",
            "reproducibility": "Run passport captures seed, git hash, scenario parameters, source fingerprints, limitations, and claim labels.",
        },
    }


def write_run_passport(passport: dict[str, Any], path: str | Path) -> Path:
    output = Path(path)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(passport, indent=2, ensure_ascii=True), encoding="utf-8")
    return output


def default_data_sources() -> list[dict[str, Any]]:
    return [
        {
            "id": "roads-geojson",
            "label": "Almaty road geometry",
            "path": "data/almaty_roads.geojson",
            "claim_label": "real-data",
            "source_type": "cached/imported geometry",
            "freshness": "local file snapshot",
            "notes": "Treat as imported/cached road geometry, not live traffic.",
        },
        {
            "id": "traffic-density",
            "label": "Prototype traffic density",
            "path": "data/traffic_data.json",
            "claim_label": "demo",
            "source_type": "local demo dataset",
            "freshness": "local file snapshot",
            "notes": "Density values are prototype/demo inputs.",
        },
        {
            "id": "analytics-normal-abay",
            "label": "Abay analytics proxy",
            "path": "data/analytics_normal_abay.json",
            "claim_label": "proxy",
            "source_type": "generated proxy analytics",
            "freshness": "generated locally",
            "notes": "Generated by scripts/generate_analytics.py; values are transparent proxies.",
        },
        {
            "id": "calibration-layer",
            "label": "Almaty calibration layer",
            "path": "data/calibration/almaty_calibration_layer.json",
            "claim_label": "proxy",
            "source_type": "curated calibration assumptions",
            "freshness": "local file snapshot",
            "notes": "Used as calibration assumption evidence until observed-vs-sim data is attached per run.",
        },
        {
            "id": "corridor-pack-abay",
            "label": "First Corridor Pack - Abay",
            "path": "docs/obsidian/03-registries/First Corridor Pack - Abay.md",
            "claim_label": "proxy",
            "source_type": "Obsidian corridor anchor",
            "freshness": "2026-06-05 workbench note",
            "notes": "Defines first-epic decision question, measures, and required dossier fields.",
        },
        {
            "id": "provider-registry",
            "label": "Data provider registry",
            "path": "reports/data_sources/provider_registry.json",
            "claim_label": "demo",
            "source_type": "provider provenance/status registry",
            "freshness": "generated locally",
            "notes": "Lists source availability, legal mode, freshness, fallback behavior, and limitations for G010.",
        },
        {
            "id": "roads-provider-status",
            "label": "Road geometry provider status",
            "path": "reports/data_sources/roads_geojson_provider_status.json",
            "claim_label": "real-data",
            "source_type": "cached/imported OSM road geometry status",
            "freshness": "local file modification time",
            "notes": "Cached OSM-derived road geometry status; not a live feed.",
        },
    ]


def default_limitations() -> list[str]:
    return [
        "Road geometry is a local cached/imported snapshot, not a live municipal feed.",
        "Traffic density and analytics are demo/proxy values unless linked to observed source data.",
        "Calibration layer records corridor assumptions; observed-vs-simulated error is not yet attached for every run.",
        "CAPEX/OPEX and ROI values are placeholders or transparent proxies until supplied by akimat or engineering estimates.",
        "Dossier recommendation is decision-support evidence, not an automated legal or procurement decision.",
    ]


def _source_from_config(
    source: dict[str, Any],
    root: Path,
    *,
    physical_path: Path | None = None,
    source_ref: str | None = None,
) -> DataSource:
    label = _claim_label(str(source.get("claim_label", "demo")))
    path = str(source.get("path", ""))
    full_path = physical_path if physical_path is not None else root / path
    serialized_path = source_ref if source_ref is not None else path
    available = full_path.exists()
    if label == "real-data" and not available:
        label = "demo"
    return DataSource(
        id=str(source.get("id", path or "source")),
        label=str(source.get("label", source.get("id", path))),
        path=serialized_path,
        claim_label=label,
        source_type=str(source.get("source_type", "local file")),
        available=available,
        sha256=_sha256(full_path) if available and full_path.is_file() else None,
        bytes=full_path.stat().st_size if available and full_path.is_file() else None,
        freshness=str(source.get("freshness", "local workspace snapshot")),
        notes=str(source.get("notes", "")),
    )


def _normalize_claim_labels(labels: dict[str, str]) -> dict[str, str]:
    return {str(key): _claim_label(str(value)) for key, value in labels.items()}


def _claim_label(value: str) -> str:
    if value not in CLAIM_LABELS:
        raise ValueError(f"Unsupported claim label: {value}. Expected one of {sorted(CLAIM_LABELS)}")
    return value


def _calibration_validation(
    path: str | Path,
    *,
    display_path: str | None = None,
) -> dict[str, Any]:
    calibration_path = Path(path)
    serialized_path = display_path if display_path is not None else str(calibration_path)
    if not calibration_path.exists():
        return {
            "claimLabel": "demo",
            "path": serialized_path,
            "available": False,
            "notes": "Calibration layer file not found.",
            "observedVsSimulated": [],
        }
    payload = json.loads(calibration_path.read_text(encoding="utf-8"))
    return {
        "claimLabel": "proxy",
        "path": serialized_path,
        "available": True,
        "segmentCount": len(payload.get("segments", [])),
        "intersectionCount": len(payload.get("must_calibrate_intersections", [])),
        "observedVsSimulated": [],
        "notes": "Calibration layer contains corridor and intersection assumptions; per-run observed-vs-simulated rows remain a limitation until attached.",
    }


def _resolve_source_context(
    sources: list[dict[str, Any]],
    *,
    root: Path,
    source_paths: Mapping[str, str | Path] | None,
    source_refs: Mapping[str, str] | None,
) -> dict[str, tuple[Path, str]]:
    source_ids = [str(source.get("id", "")) for source in sources]
    if any(not source_id for source_id in source_ids) or len(source_ids) != len(set(source_ids)):
        raise ValueError("Every data source must have one unique non-empty id")
    expected = set(source_ids)
    if source_paths is None:
        if source_refs is not None:
            raise ValueError("source_paths is required when source_refs is explicit")
        return {
            source_id: (root / str(source.get("path", "")), str(source.get("path", "")))
            for source_id, source in zip(source_ids, sources, strict=True)
        }

    _require_exact_roles(source_paths, expected, map_name="source_paths")
    if source_refs is None:
        raise ValueError("source_refs is required when source_paths is explicit")
    _require_exact_roles(source_refs, expected, map_name="source_refs")
    return {
        source_id: (
            Path(source_paths[source_id]),
            _logical_ref(source_refs[source_id], role=source_id),
        )
        for source_id in source_ids
    }


def _project_context(
    root: Path,
    context: Mapping[str, Any] | None,
    *,
    explicit_sources: bool,
) -> dict[str, Any]:
    if context is None:
        if explicit_sources:
            raise ValueError("project_context is required when source_paths is explicit")
        return {
            "name": "traffic-sim-almaty",
            "version": _project_version(root),
            "gitHash": _git_hash(root),
        }
    required = {"name", "version", "gitHash"}
    missing = sorted(required - set(context))
    if missing:
        raise ValueError(f"Invalid project_context: missing={missing}")
    return {
        "name": str(context["name"]),
        "version": str(context["version"]),
        "gitHash": None if context["gitHash"] is None else str(context["gitHash"]),
    }


def _resolved_calibration_context(
    *,
    calibration_path: str | Path,
    calibration_context: Mapping[str, Any] | None,
    resolved_sources: Mapping[str, tuple[Path, str]],
    explicit_sources: bool,
) -> dict[str, Any]:
    if calibration_context is not None:
        required = {"claimLabel", "path", "available", "observedVsSimulated", "notes"}
        missing = sorted(required - set(calibration_context))
        if missing:
            raise ValueError(f"Invalid calibration_context: missing={missing}")
        payload = dict(calibration_context)
        payload["claimLabel"] = _claim_label(str(payload["claimLabel"]))
        payload["path"] = _logical_ref(str(payload["path"]), role="calibration")
        payload["available"] = bool(payload["available"])
        if not isinstance(payload["observedVsSimulated"], list):
            raise ValueError("calibration_context.observedVsSimulated must be a list")
        return payload

    if explicit_sources:
        calibration_source = resolved_sources.get("calibration-layer")
        if calibration_source is None:
            raise ValueError(
                "calibration_context is required when explicit sources omit calibration-layer"
            )
        return _calibration_validation(
            calibration_source[0],
            display_path=calibration_source[1],
        )
    return _calibration_validation(calibration_path)


def _require_exact_roles(
    values: Mapping[str, object],
    expected: set[str],
    *,
    map_name: str,
) -> None:
    actual = set(values)
    missing = sorted(expected - actual)
    unknown = sorted(actual - expected)
    if missing or unknown:
        raise ValueError(f"Invalid {map_name}: missing={missing}, unknown={unknown}")


def _logical_ref(value: str, *, role: str) -> str:
    raw = str(value)
    path = PurePosixPath(raw)
    if (
        not raw
        or raw != raw.strip()
        or "\\" in raw
        or path.is_absolute()
        or ".." in path.parts
        or any(".staging" in part for part in path.parts)
        or (path.parts and path.parts[0].endswith(":"))
        or path.as_posix() != raw
    ):
        raise ValueError(f"Unsafe logical reference for {role}: {raw!r}")
    return path.as_posix()


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as file:
        for chunk in iter(lambda: file.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _git_hash(root: Path) -> str | None:
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"],
            cwd=root,
            check=True,
            capture_output=True,
            text=True,
        )
    except (subprocess.CalledProcessError, OSError):
        return None
    return result.stdout.strip() or None


def _project_version(root: Path) -> str:
    pyproject = root / "pyproject.toml"
    if not pyproject.exists():
        return "unknown"
    for line in pyproject.read_text(encoding="utf-8").splitlines():
        if line.strip().startswith("version"):
            return line.split("=", 1)[1].strip().strip('"')
    return "unknown"
